# Generated by Django 3.2 on 2022-02-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_spotless_app', '0002_auto_20220220_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
