# Generated by Django 3.2 on 2022-02-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_spotless_app', '0003_alter_contact_replied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approved',
            field=models.IntegerField(choices=[(0, 'Waiting for approval'), (1, 'Approved'), (1, 'In progress'), (2, 'Blocked'), (3, 'Done')], default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='replied',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=False),
        ),
    ]
