# Generated by Django 3.2 on 2022-02-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_spotless_app', '0004_rename_upcoming_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('weekly', 'Weekly Cleaning'), ('general', 'General Cleaning'), ('moveout', 'Moveout Cleaning'), ('window', 'Window Cleaning'), ('gardening', 'Gardening'), ('craft', 'Simpler Crafts'), ('recycling', 'Recycling'), ('relocation', 'Relocation Assistance')], default='Weekly Cleaning', max_length=30),
        ),
    ]
