# Generated by Django 3.2 on 2022-02-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_spotless_app', '0004_auto_20220227_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='approved',
            new_name='state',
        ),
    ]
