# Generated by Django 3.2 on 2022-02-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_spotless_app', '0005_rename_approved_booking_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.IntegerField(choices=[(0, 'WAITING FOR APPROVAL'), (1, 'APPROVED'), (1, 'IN PROGRESS'), (2, 'BLOCKED'), (3, 'DONE')], default=False),
        ),
    ]
