# Generated by Django 3.2 on 2022-02-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_spotless_app', '0007_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_requisite',
            new_name='requisite',
        ),
    ]
