# Generated by Django 3.2 on 2022-02-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_spotless_app', '0010_rename_services_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default='Subject Missing', max_length=100),
        ),
    ]
