# Generated by Django 3.2 on 2022-02-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_spotless_app', '0012_alter_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
